systemLog:
   destination: file
   path: /var/vcap/sys/log/mongodb/mongod.log
   logAppend: true
storage:
  dbPath: /var/vcap/store/mongodb
processManagement:
  pidFilePath: /var/vcap/sys/run/mongodb/mongod.pid
