#!/bin/bash -e

LOG_DIR=/var/vcap/sys/log/mongodb
DB_DIR=/var/vcap/store/mongodb

ensure_dir() {
  local dir="$1"
  local user_and_group="$2"

  mkdir -p "$dir"
  chown "$user_and_group" "$dir"
}

main() {
  ensure_dir "$LOG_DIR" vcap:vcap
  ensure_dir "$DB_DIR" vcap:vcap
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  main "$@"
fi
