#!/usr/bin/env bash
set -e

source /var/vcap/jobs/mongodb/config/envs

ulimit -u 32768

/sbin/start-stop-daemon \
  --pidfile "${PIDFILE_DIR}/mongod.pid" \
  --chuid vcap:vcap \
  --start \
  --exec "$MONGOD_PATH" -- --config "$CONFIG_PATH"
