---
name: mongodb-service
blobstore:
  provider: s3
  options:
    bucket_name: booleancat-mongodb-service-release-blobs
    region: eu-west-2
    endpoint: s3.eu-west-2.amazonaws.com
    credentials_source: env_or_profile
